version: '2'
services:
  zookeeper:
    image: wurstmeister/zookeeper
  kafka:
    build: ./kafka-docker/.
    ports:
      - "9092:9092"
    environment:
      KAFKA_ADVERTISED_HOST_NAME: localhost
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
  redis:
    build: ./redis-docker/
    environment:
      - ALLOW_EMPTY_PASSWORD=yes
    ports:
      - '6379:6379'
    volumes:
      - /redis.conf:/usr/local/etc/redis/redis.conf
  mongo:
    image: mongo:4.0.9-xenial
    command: --smallfiles
    ports: 
     - "27017:27017"     
  mysql:
    build: ./mysql-docker/.
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: 
      MYSQL_DATABASE: 
      MYSQL_USER: 
      MYSQL_PASSWORD: 
    ports:
        - '3306:3306'
    volumes:
     - ./mysqldata:/data/db
